import { Pangolin } from 'next/font/google'
import { Navigation } from './components/Navigation'
import '../app/globals.css'

const pangolin = Pangolin({ subsets: ['latin'],
weight: ['400'], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <body className={pangolin.className}>
        <Navigation />
        {children}
      </body>
      </head>
    </html>
  )
}
